// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyActpi6mWY1fd7bDPrh3ALSuh1cB9N4uxI',
    appId: '1:848099422906:web:a0fbf7518c75a12a060883',
    messagingSenderId: '848099422906',
    projectId: 'trucklink-ai-orignal',
    authDomain: 'trucklink-ai-orignal.firebaseapp.com',
    storageBucket: 'trucklink-ai-orignal.firebasestorage.app',
    measurementId: 'G-Z9R9W65TQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6bI782ro5XDh043x_9Bd-JcaD-G-pMIY',
    appId: '1:848099422906:android:54dd19dfe50cfeaf060883',
    messagingSenderId: '848099422906',
    projectId: 'trucklink-ai-orignal',
    storageBucket: 'trucklink-ai-orignal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVr8fQ5Ra4as4cZjyZmadWSICJa0IK9ZE',
    appId: '1:848099422906:ios:03e14d5f712de716060883',
    messagingSenderId: '848099422906',
    projectId: 'trucklink-ai-orignal',
    storageBucket: 'trucklink-ai-orignal.firebasestorage.app',
    iosBundleId: 'com.example.trucklinkaiOrignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVr8fQ5Ra4as4cZjyZmadWSICJa0IK9ZE',
    appId: '1:848099422906:ios:03e14d5f712de716060883',
    messagingSenderId: '848099422906',
    projectId: 'trucklink-ai-orignal',
    storageBucket: 'trucklink-ai-orignal.firebasestorage.app',
    iosBundleId: 'com.example.trucklinkaiOrignal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyActpi6mWY1fd7bDPrh3ALSuh1cB9N4uxI',
    appId: '1:848099422906:web:795caf855d044657060883',
    messagingSenderId: '848099422906',
    projectId: 'trucklink-ai-orignal',
    authDomain: 'trucklink-ai-orignal.firebaseapp.com',
    storageBucket: 'trucklink-ai-orignal.firebasestorage.app',
    measurementId: 'G-QJZMX2HL2V',
  );
}
